### ISSUE TITLE
BUG: html repr not legible in dark themes

### ISSUE THREAD

**Issue by martinfleis** [geopandas/xyzservices#66]
Our HTML repr works only in light IDE themes like the default JLab. Dark mode makes it illegible.

![Screenshot 2021-08-05 at 11 08 18](https://user-images.githubusercontent.com/36797143/128332840-2ea3c878-ca5a-45d1-b845-be280f2060fa.png)

**Comment by benbovy** [comment]
Since you have been inspired by xarray for this repr, I just want to mention the following PRs in case you haven't checked it yet:

- https://github.com/pydata/xarray/pull/3443
- https://github.com/pydata/xarray/pull/4036
- https://github.com/pydata/xarray/pull/5201

(more off-topic: I also like the recently added reprs for dask clusters and clients, e.g., https://github.com/dask/distributed/pull/4857)

**Comment by martinfleis** [comment]
@benbovy thanks a lot for the references! It looks like a lot of fun ahead.
